stages:
  - test


test:
  stage: test
  image: python:3.6-alpine3.6
  variables: 
    PYTHONPATH: /usr/lib/python3.6/site-packages/
  script:
    - apk add --no-cache postgresql-dev libffi-dev build-base linux-headers
    - pip install -r requirements.txt
    - pytest
