language: python
python:
  - "3.6"

env:
  global:
    - POSTGRES_PASSWORD=
    - POSTGRES_USER=
    - POSTGRES_DB=
    - COALICS_CSRF_KEY=
    - PYTHONPATH=.

install:
  - pip install -r requirements.txt

services:
  - redis-server

script:
  - pytest
