version: '3.2'
services:
  app:
    env_file: 
     - .env
     - .env.dev
    volumes:
      - .:/app:rw
  # worker:
  #   env_file: 
  #    - .env
  #    - .env.dev
  #   volumes:
  #     - .:/app:rw

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080