version: '3.2'

services:
  app:
    build: .
    user: nobody
    ports:
      - "8080:8080"
    environment:
      - FLASK_DEBUG=1 
      - FLASK_APP=app/__init__.py
    volumes:
      - .:/app:rw
      #- 'database:/data'
      - ./database:/data:rw
    command: ./dev.sh 

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server #--requirepass devpassword
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

volumes:
  redis:
  database:
