version: '3.2'

services:
  app:
    build: .
    image: registry.gitlab.com/paulgessinger/coalics/app:dev
    user: nobody
    hostname: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./log:/app/log:Z
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "run.py"]


  worker:
    build: .
    image: registry.gitlab.com/paulgessinger/coalics/app:dev
    user: nobody
    hostname: app
    depends_on:
      - db
      - app
    volumes:
      - ./log:/app/log:Z
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "coalics/schedule.py"]


  db:
    image: 'postgres:10.0-alpine'
    env_file: .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
