version: '3.2'

services:
  app:
    build: .
    user: nobody
    depends_on:
      - redis
      - db
    ports:
      - "8080:8080"
    environment:
      - FLASK_DEBUG=1 
      - FLASK_APP=app
    volumes:
      - .:/app:rw
      #- 'database:/data'
      #- ./database:/data:rw
    command: ./dev.sh 

  redis:
    image: 'redis:3.0-alpine'
    command: redis-server #--requirepass devpassword
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  db:
    image: 'postgres:10.0-alpine'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql

  #db:
    #image: mariadb
    #restart: always
    #environment:
      #MYSQL_ROOT_PASSWORD: example
    #volumes:
      #- ./mariadb:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080

volumes:
  redis:
  database:
