version: '3.2'

services:
#  app:
#    build: .
#    hostname: app
#    depends_on:
#      - db
#    ports:
#      - "5000:5000"
#    env_file: .env
#    working_dir: /src
#    volumes:
#      - ./:/src

  db:
    image: 'postgres:10.0-alpine'
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
