version: '3.2'


services:
  app:
    env_file: 
     - .env
     - .env.prod
    image: registry.gitlab.com/paulgessinger/coalics/app:prod
    ports: []
    expose:
      - "8080"

  worker:
    env_file: 
     - .env
     - .env.prod
    image: registry.gitlab.com/paulgessinger/coalics/app:prod

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - app


