version: '3.2'

services:
  app:
    image: registry.gitlab.com/paulgessinger/coalics/app:prod
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=app
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes: []
    command: ./prod.sh
    ports: []
    expose:
      - "8080"

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    depends_on:
      - app


