"""empty message

Revision ID: 710d54699d93
Revises: 9f98c73ea81f
Create Date: 2017-10-29 14:52:20.193199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "710d54699d93"
down_revision = "9f98c73ea81f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("active", sa.Boolean(), server_default="1", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "active")
    # ### end Alembic commands ###
