"""empty message

Revision ID: cea006e74b5c
Revises: 12f833559028
Create Date: 2017-10-25 20:45:46.955937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cea006e74b5c"
down_revision = "12f833559028"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("calendar", sa.Column("slug", sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, "calendar", ["slug"])
    op.drop_constraint("calendar_owner_id_fkey", "calendar", type_="foreignkey")
    op.create_foreign_key(
        None, "calendar", "user", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "calendar", type_="foreignkey")
    op.create_foreign_key(
        "calendar_owner_id_fkey", "calendar", "user", ["owner_id"], ["id"]
    )
    op.drop_constraint(None, "calendar", type_="unique")
    op.drop_column("calendar", "slug")
    # ### end Alembic commands ###
