"""empty message

Revision ID: e261a8586dc6
Revises: 710d54699d93
Create Date: 2017-10-29 15:36:53.411418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e261a8586dc6"
down_revision = "710d54699d93"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_username_key", "user", type_="unique")
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "username", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
    )
    op.create_unique_constraint("user_username_key", "user", ["username"])
    # ### end Alembic commands ###
