"""empty message

Revision ID: e7607c2bc445
Revises: 1c02b13b8990
Create Date: 2017-09-30 16:40:38.993823

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "e7607c2bc445"
down_revision = "1c02b13b8990"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calendar",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "calendar_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sqlalchemy_utils.types.url.URLType(), nullable=True),
        sa.Column("positive_pattern", sa.String(length=255), nullable=True),
        sa.Column("negative_pattern", sa.String(length=255), nullable=True),
        sa.Column("alerts", sa.String(length=255), nullable=True),
        # sa.Column('alerts', sqlalchemy_utils.types.scalar_list.ScalarListType(), nullable=True),
        sa.Column("calendar_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["calendar_id"], ["calendar.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calendar_source")
    op.drop_table("calendar")
    # ### end Alembic commands ###
