---
- hosts: all
  vars:
    app_dir: /srv/coalics
  tasks:
    - name: Install pip
      apt: name=python-pip state=present
      become: yes

    - name: Install pip packages
      pip: name="{{ item }}"
      with_items:
        - docker

    - name: Ensure docker is running
      service: name=docker state=started

    - name: Ensure nginx is running
      service: name=nginx state=started

    - name: Update git repository
      git:
        repo: https://github.com/paulgessinger/coalics.git
        dest: "{{ app_dir }}"
        update: yes
        clone: yes
        version: master
      #notify: rebuild containers
      #
    - name: Build containers
      docker_service:
        project_src: "{{ app_dir }}"
        files:
          - docker-compose.yml
          - production.yml
        state: present
        restarted: yes

    - name: Install logrotate
      file:
        src: files/logrotate_coalics
        dest: /etc/logrotate.d/coalics
      become: yes
